language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: ideavoter
  on:
    branch: prod
    node: '6'
  api_key:
    secure: nVNd8zGcgGWNJekDuu3/p58C6B26p/WFqFv3SmNkn2Ekfm3Xby/14Lc3itqkxAElcsS330sZACbW2Yo0Y7LTsVstilDSNzRG/5ckQLNX1yBVzHMwCQ1RntU/uBypZXnfej9KRQkxI+imEyAl5Dx1YGa5nq8YDiHnlWBIY4F7AJhFmC8aGk5ECBX9ZjV6zeHkzhydunovnllVVkavY6n1RVvCSUn9r8N2o8Rkdd+60J5ZLIXFDdE8lGCwpwPxyjkLMy8VIa/xZ+Cq+i/NnZ0Y4xjeWttEvA5BR2boaLPQ508vB8fmSnn+Ka5+R56PrvzhLQtp95qbXGz95wiuQNDvaRHLsVGFISOCG82NfJwptv/gR75bTKiQ6R0a5oSSw7qeFn3yUcQtMqPmvS3VW6c2K0RaiXqsyTiPejPAOxidB97Gn/+xq5gh+iORluDYjwl2jEzLVO4G2w1LvqnB0Gpe5/aHUY2Vr1g2STMUrSVewo/JCZ7qK5UqGyvAKb+5Ew5wkTwNoJxlrTfsUrY2OQ7ztzdLLlFNE5bg66JceT7hcKNkGLzPgpEOGhIsw8qfyxJ/MAr9NXN6oMMgCvS78jLMYrk0MsYbNwwzetLz1yMpAP/zF8AwRSJJ7BEXEiaXsFKtd7C1H3rJjB56v2II+0TK8PkOb62zGP5bwzsdiPhluVU=
