language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: ideavoter
  on:
    branch: prod
    node: '6'
  api_key:
    secure: Y3/bTU/dr7H4VE77T4zkBnqRTBSSSrGp/WQuYxye2hiOg6XLpWTgunD4FjWE3pnGWu9gRlBDbFKQVhazet8udmVWNM/c8g5uyW6C20noz9CwhTvWTSEcGd0yJ/iaJxjZt1gEW1unRW5jf51HEI3XKI0qwQPrkk76RUJBK6RpiYx2frz9i4Al3WhNRsq9+zDaS+oV8I04QMEWFvi/NjGc187RR6WvHq3oMvV8IhIJpqcC/mKk+70jXbyyUYylzH2rNAV2/Les66gIIC5BmP0ycCq+BDhZDWY0dCc7U30Rz92Xw1W2qXnggH7kZB5MPXLRfIuBWTSuIs9enCyVuAvwY2Aj4MGfkew8V5XhT7BksC63cdkEtrsS4B8oaqP9NE7SiEOkObwu+9w2mTUyk48dPo+jYBrLD2kNKe4jIJnR3CVzyojTYOvk91aVhLEsiQhKxe94HLOGyi00Pta1idj+boWbl9PHAF6amlyGLAAkfbnbgd5OmVaE68Wl4SbkmwpC2nm6NZE2mZS6av15ooWsQHte23zKU8dE1ecpx7N/4pk0RoV3oOn0h7NEKRoC8AYIi87M1mG+qsSGA9yFVRCBXBdkn545BqI1ZbY7Vp7E8h5UBkMrD4itEPbjiMB5zIfS3G3l+0GR574aJIdSFc92O81wBu2stHksAY/wAqsE1sM=
