language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: ideavoter
  on:
    branch: prod
    node: '6'
  api_key:
    secure: uKV2HHufZRP0Vz8F3mnuX7RIYQq1zOMUj/cuiKXI5wpjqhUbGsWxeCIHpJYWtHt03glNRM06wG+9l4EHsfmI87FIyVGPdtv+Q0wv65v8zrGldG8uuM8KzRlAEu92VbhPDlik0CxsD/GGd8UZMm3Fka64J7/PDwtFU/mrRtKV8x2+rbmUprmELvJV0LKuxh6CtmfBWgmWb0wZ4vDr89dh3MnbRthN94yXYOl3PEE5a9OQJJWde/ydls2sy70cABSc2ImCrnDFc9gU+hVig9Osl4eADaj8zrpnXWvHKh6WYMrcMLUXt+XeyQ7nyo+/q5r1FVwma/CMu6YkQkozKW9uKVJoSkZFRsWRw74FaI8E+Ek2a7O0wj0+Hfery5AVDDM4xdpLoWD/MwB6WliPUrbm/ZsK0UgkQk3fyvpGN4IJBXw5TtFu71PsLAoq7A4/UR49lDPP0G0GNpt9MauGl10/EBWcuEhUCgvhHU7jTU4qU3+KU4cEjXMW4npqLpcJc5hDZAAVhOgGb6Esqc/+7CyDovbLAvy1xHSg+YhLQPKmunfz9h0iLr3HWPyYOquEyN1Zch9NG3L/g4slJEBIE9POghmcGjxDmmHWYDuVn8QyUMWw6O/HE58RG53KvDCfEG5l7Q4SLoDBW25AeqttWZr0qk+uWLxl95Lp9IfqFq9Yq2k=
