language: node_js
node_js:
- '6'
cache:
  directories:
    - node_modules
script:
  - npm test
deploy:
  provider: heroku
  app: ideavoter
  on:
    branch: prod
    node: '6'
  api_key:
    secure: T8UhbymGBKNaPpPTrjhuy3Rlsan11iCJ6Rj74QMA5jWWrzhttn7eQh0wibotmXsTa1yMqcpvn0SBcUJUD12aT60WWJ0KxGcGwe60N69gzurG3GBifEwwZq3xX8nMalXf9eYjZV0ReXUpLfjVUnY2jyxYSJqz8xb3FTw3DrfT2YjY/0UsvahzmIIliIN1+Wic6Nc9Pd0DGcXawqtmk0GyhDohBX9D6tP/qjecByU+DqfAa1L3EWqxQGaMqXp4ZIGcMT0J3uQqXxNKaKz/JAt9k5jWfplDrhNrDptO7I95qMizpPfMoX4DlPscB7B5POLmMkVcMe7tAHkfwEDl8aA33WZEG459KN0y4kdSXHrRzMX6ZxNaz9VYWXSY2aQlxiupN01hPXC6FkslB7g5dtCH4p1xV5SaMlc6yFtOwJxkCgkMxuXII9psNSY4bkOgou1fGRrFJnjyC0KjGpCo/kiCNbGqtgjc4hSjtmaCVuJlmEHpuVG5xR4CCnsdOuNW1qskKZXLi9yFror/XUThlKi3ZGCe+ZNrfz75uoY0nCOPG+MeSmaqdQC22QSU9QJBX1M16JrPRDhCxOK/uCETXhkwST2EJtgdZrsS7Cm/NdfxOZ4RR4V82uKgHowLH6RkdC8E05zPrDvCgGpUPOuvQMiHs/G0r71HjDudwLng+e4KvuQ=
